mainpower <- read.table("Downloads/household_power_consumption.txt",skip=1,sep=";")
names(mainpower) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subsetpower <- subset(mainpower,power$Date=="1/2/2007" | mainpower$Date =="2/2/2007")
hist(as.numeric(as.character(subsetpower$Global_active_power)),col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
title(main="Global Active Power")