mainpower <- read.table("Downloads/household_power_consumption.txt",skip=1,sep=";")
names(mainpower) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
sub_set_power <- subset(mainpower,mainpower$Date=="1/2/2007" | mainpower$Date =="2/2/2007")
sub_set_power$Date <- as.Date(sub_set_power$Date, format="%d/%m/%Y")
sub_set_power$Time <- strptime(sub_set_power$Time, format="%H:%M:%S")
sub_set_power[1:1440,"Time"] <- format(sub_set_power[1:1440,"Time"],"2007-02-01 %H:%M:%S")
sub_set_power[1441:2880,"Time"] <- format(sub_set_power[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(sub_set_power$Time,sub_set_power$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
with(sub_set_power,lines(Time,as.numeric(as.character(Sub_metering_1))))
with(sub_set_power,lines(Time,as.numeric(as.character(Sub_metering_2)),col="red"))
with(sub_set_power,lines(Time,as.numeric(as.character(Sub_metering_3)),col="blue"))
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
title(main="Energy sub-metering")
